// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// qspi //
// ---- //

#define qspi_wrap_target 0
#define qspi_wrap 1

static const uint16_t qspi_program_instructions[] = {
    //     .wrap_target
    0x7004, //  0: out    pins, 4         side 0
    0xb842, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qspi_program = {
    .instructions = qspi_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config qspi_program_get_default_config(uint offset)
{
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qspi_wrap_target, offset + qspi_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif
