WAVESHARE_LCD_MOD_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/waveshare_lcd.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/lcd.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/font8.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/font12.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/font16.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/font20.c
SRC_USERMOD += $(WAVESHARE_LCD_MOD_DIR)/font24.c

# We can add our module folder to include paths if needed
CFLAGS_USERMOD += -I$(WAVESHARE_LCD_MOD_DIR)
